### PR TITLE
Create RespawnCommand.cs

### PR DESCRIPTION
**Pull request by xAstroBoy**

### CODE REVIEW

**Comment by winstxnhdw** [comment]
@xAstroBoy Doesn't seem to work for me :/

**Comment by xAstroBoy** [comment]
it works, for me atleast even in vanilla.

**Comment by winstxnhdw** [comment]
I am on vanilla as well. I go on a multiplayer lobby. Land the ship. Run into the factory. Jump off the railings and die. Then do `/respawn`. Nothing happens.

**Comment by xAstroBoy** [comment]
> Have you tried with this branch?

yes i did

**Comment by xAstroBoy** [comment]
Just a random death.

**Comment by winstxnhdw** [comment]
I see. So being killed by fall damage won’t work with this?

**Comment by xAstroBoy** [comment]
> I see. So being killed by fall damage won’t work with this?

it should, because is basically a modified .RespawnAllPlayers()

**Comment by winstxnhdw** [comment]
I just tested again. This time I had a friend kill me with a shovel. Doesn’t work.

**Comment by xAstroBoy** [comment]
> I just tested again. This time I had a friend kill me with a shovel. Doesn’t work.

i might have a idea how to fix this command and make it better.
But for now let's focus on the other two pull requests which are ready to be merged.

**Comment by winstxnhdw** [comment]
GitHub is broken in my region for some reason. I can only access it via my phone right now, so you’ll have to wait.

**Comment by xAstroBoy** [comment]
@winstxnhdw  try this new version

**Comment by winstxnhdw** [comment]
Tested. It works.

**Pull request merged**
