### PR TITLE
feat/docs: add `rejoin` bind

### PR DESCRIPTION
**Pull request by winstxnhdw**
## Summary

- Rejoin recently joined lobby with `Shift` + `F5`.
- If your clipboard contains a valid Steam ID, the bind will join that lobby instead.
- All in only 27 lines

@D1GQ, apologies for not using your original PR. There were too many merge conflicts when pulling. Always do [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) before creating a new PR if you want to prevent them from happening. Also, please review and see if I am missing any of your features or if you think something should be implemented differently.

Closes #343 and #342

### CODE REVIEW

**Comment by joep26020** [comment]
not working

**Comment by Totoqoe** [comment]
> not working

I believe this is a separate branch so it wont auto update

**Comment by joep26020** [comment]
> > not working
> 
> I believe this is a separate branch so it wont auto update

? so how do i use it?

**Comment by D1GQ** [comment]
> ## Summary
> * Rejoin recently joined lobby with `Shift` + `F5`.
> * If your clipboard contains a valid Steam ID, the bind will join that lobby instead.
> * All in only 27 lines
> 
> @D1GQ, apologies for not using your original PR. There were too many merge conflicts when pulling. Always do [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) before creating a new PR if you want to prevent them from happening. Also, please review and see if I am missing any of your features or if you think something should be implemented differently.
> 
> Closes #343 and #342

Everything looks fine but it would be nice if some Lobby information would be displayed in the top right and have it toggle like this.

Screenshot 2024-02-02 191328
Screenshot 2024-02-02 191348

**Comment by Totoqoe** [comment]
> > > not working
> > 
> > 
> > I believe this is a separate branch so it wont auto update
> 
> ? so how do i use it?
make a new folder for the branch and run this command 
`git clone -b feat/rejoin --single-branch --recursive https://github.com/winstxnhdw/lc-hax.git`

**Comment by winstxnhdw** [comment]
> > ## Summary
> > 
> > * Rejoin recently joined lobby with `Shift` + `F5`.
> > * If your clipboard contains a valid Steam ID, the bind will join that lobby instead.
> > * All in only 27 lines
> > 
> > @D1GQ, apologies for not using your original PR. There were too many merge conflicts when pulling. Always do [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) before creating a new PR if you want to prevent them from happening. Also, please review and see if I am missing any of your features or if you think something should be implemented differently.
> > Closes #343 and #342
> 
> Everything looks fine but it would be nice if some Lobby information would be displayed in the top left and have it toggle like this. It would also be nice to have a disconnect then rejoined bind to be sure that you're the last player in the lobby for antikick.
> 
> Screenshot 2024-02-02 191328 Screenshot 2024-02-02 191348

Why do we need another bind for disconnecting and rejoining when the user can just hold shift, press F4 then F5?

**Comment by winstxnhdw** [comment]
I think if there are no objections by the end of today, I'll go ahead with this.

**Comment by D1GQ** [comment]
> I think if there are no objections by the end of today, I'll go ahead with this.

Yeah you can add a command that's fine but it would still be nice if there was some type of debug feature to have it, I added it myself for reasons of that nature, and it would be beneficial to have a rejoin button because if you have a steam ID in your clipboard you wouldn't be able to do F4 then F5 because you would just attempt to join the steam ID.

**Comment by winstxnhdw** [comment]
> you wouldn't be able to do F4 then F5 because you would just attempt to join the steam ID.

I've thought of that. The clipboard is cleared after the user joins a lobby so this doesn't happen.

**Pull request merged**
