### PR TITLE
feat/fix: `/hitclick` added, stunclick fix, wait for ship fix, invis fix

### PR DESCRIPTION
**Pull request by armorfid**

### CODE REVIEW

**Comment by armorfid** [comment]
feel free to refactor StunMod if you wanna separate hitclick

**Review by winstxnhdw — APPROVED** [review]
I have no problems with this. Great work as always!

**Comment by winstxnhdw** [comment]
@armorfid out of curiosity, why did you remove `isDefensiveWeapon`? Does it not work?

**Comment by winstxnhdw** [comment]
Oops, you're right. The green highlight appears red in my room's lighting. My bad 😂

**Pull request merged**
