### PR TITLE
Update VisitCommand.cs

### PR DESCRIPTION
**Pull request by xAstroBoy**
Make it print Available levels over it.

### CODE REVIEW

**Comment by winstxnhdw** [comment]
Why is this necessary?

**Comment by xAstroBoy** [comment]
Doing a few more adjustements rn, and yeah is because the terminal have specify strings such as different names off there, which it would be nice to print the available levels other than just unknowingly put the wrong value and not know if you picked the right moon to visit.

**Comment by winstxnhdw** [comment]
Why not just have a print at the end that says "Visiting {moon}.."?

**Comment by xAstroBoy** [comment]
> Why not just have a print at the end that says "Visiting {moon}.."?

That can be done, but still is nice to know what moon are available just by printing the moons when someone puts a invalid number or name.

**Comment by xAstroBoy** [comment]
> I assume if a user wants to visit a moon, they already have the place in mind. It's not exactly the job of this cheat to tell the user what moons there are. That's the game's job.

Yeah, but the visit command uses the enum list directly, not the terminal names, which makes it slightly a bit different

**Comment by xAstroBoy** [comment]
> Oh, I see. Then we should use the new FuzzyMatch helper I added. I can make the change if you want.

Go ahead, is your mod!

**Pull request merged**
