### PR TITLE
Lobby ID/Steam ID: Display & Clipboard Copy/Paste

### PR DESCRIPTION
**Pull request by D1GQ**
### Lobby ID/Steam ID: Display & Clipboard Copy/Paste
Added a few changes evolving around Lobby ID, the biggest changes is the fact that you can copy and paste into the current Lobby ID, this is very useful because the lobby ID is actually the host Steam ID no matter what, so if you have someones Steam ID by copying it or just having it, you can forcefully join their game even if it's private.

### Changes
- Made it where the current/last Lobby ID is displayed in the top right, note the lobby ID is actually the host steam ID.
- Made it where you can copy the current Lobby ID with `Shift + C`
- Made it where you can paste from your clipboard into the current Lobby ID with `Shift + V`

### CODE REVIEW

**Comment by winstxnhdw** [comment]
I like the idea, but not the way we are doing it here.

**Comment by D1GQ** [comment]
> I like the idea, but not the way we are doing it here.

What's the problem?

**Comment by winstxnhdw** [comment]
It sucks that so much complexity is being added despite how simple the concept and how mature the codebase already is.

I don’t even know if this is a better idea but I think we should just read directly from the Windows clipboard. If the Windows clipboard contains a valid Steam ID, performing the rejoin bind will connect to that room.

**Comment by winstxnhdw** [comment]
It’s crazy how we need 46 line additions, 2 more binds and 1 entirely new mod to achieve something this simple.

**Comment by D1GQ** [comment]
That would definitely be better, but I won't have to time to work on all of that.

**Comment by winstxnhdw** [comment]
I think if both of us don’t have time to work on this, it’s best to leave it as an issue and maybe we can implement it at a later date.

**Comment by D1GQ** [comment]
Sounds good, I'll see what I can do tho, we'll I'm going to bed.

**Comment by D1GQ** [comment]
Just thought about it I pretty much already have that functionality with the F3 implementation in the issues  I might just make it work when you click F3 it uses Steem ID form your clipboard.

**Comment by xAstroBoy** [comment]
@D1GQ i wonder if we can improve anti-kick with a few more fixes because when you join it says Player 0- how many players are in that lobby, which im sure we can fix and feed the names back there somewhere in the code.

**Comment by winstxnhdw** [comment]
I doubt. The names information is provided from the host. If you take a look at the Anti-Kick patch, you can see that I am already attempting to fix it by forwarding the player names to the client RPC, yet it still doesn’t work.

**Comment by xAstroBoy** [comment]
> I doubt. The names information is provided from the host. If you take a look at the Anti-Kick patch, you can see that I am already attempting to fix it by forwarding the player names to the client RPC, yet it still doesn’t work.

then update the player names themself without the RPC?

**Comment by winstxnhdw** [comment]
I am saying I don’t think we even have those information.

**Comment by D1GQ** [comment]
Yeah I have no idea how to bypass that.

**Comment by D1GQ** [comment]
So do you want me to make any changes?

**Comment by winstxnhdw** [comment]
I don’t think we’ll move forward with this method as stated above.

**Comment by D1GQ** [comment]
Ok, I'll keep this branch open for a while so if anyone's out there interested using it.

**Pull request closed without merging**
