### PR TITLE
Need Help!

### PR DESCRIPTION
**Pull request by MelvinShwuaner**
I want to control old birds with this mod, so i tried taking code from control code and modded it to work this game, it does work, you can control the old bird to shoot missiles or not, but it only works on host! you need noclip to move on clients and you cant shoot missiles if you are a client

my code probably sucks, this is my first time modding lethal company

## Summary by CodeRabbit

- **New Features**
	- Introduced a new enemy type, RadMechAI, with distinct behaviors for idle and attacking states.
	- Enhanced enemy control with new methods for skill activation and behavior management.

- **Improvements**
	- Made the CharacterMovement property publicly accessible for better integration with external classes. 

- **Bug Fixes**
	- Improved enemy firing state synchronization based on behavior conditions.

### CODE REVIEW

**Comment by MelvinShwuaner** [comment]
Oh yea my bad, forgot to private it after making it public

**Comment by winstxnhdw** [comment]
See our discussion #496

**Comment by MelvinShwuaner** [comment]
Huh, didn't see that 😔

**Comment by MelvinShwuaner** [comment]
well you could make it possible to control old birds if your a host right?

**Comment by winstxnhdw** [comment]
Host-only controls is not a priority for us. There's already existing mods for that, like ControlCompany.

**Comment by MelvinShwuaner** [comment]
one more thing, it is very easy to accidentally go through the entrance / fire doors when chasing a player, which i had to fix, would be nice if you could add a toggle for that, or just make it so only mimics can go through (you can go between outside and inside by turning on noclip and flying)

**Comment by winstxnhdw** [comment]
I believe the door helps to toggle the environment settings. This means that if you flew out onto land, the game still thinks that you are indoors and there are some unexpected consequences to that, depending on what mob you are controlling. E.g. if you flew out with Bracken, you can crash the entire game.

**Comment by MelvinShwuaner** [comment]
Oh wow never knew that

**Pull request closed without merging**
